version: "3"
services: 
    node-app:
        build: 
            context: . 
            args:
                NODE_ENV: development    
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE-ENV=development
            - MONGO_USER=mdkhaki
            - MONGO_PASSWORD=example
            - SESSION_SECRET=thisisalongsecret
        command: npm run dev
    mongo: 
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=mdkhaki
            - MONGO_INITDB_ROOT_PASSWORD=example        

                    

            