version: "3"
services: 
    node-app:
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE-ENV=development
        command: npm run dev
            
            